### PR TITLE
NodeJS EvalMode

### PR DESCRIPTION
**Pull request by NQNStudios**
I'm having the same problem with this implementation as with the python PR (#28)

### CODE REVIEW

**Comment by NQNStudios** [comment]
I figured that bug out. Now I have this working, but there's something about the JS target that I want to run by you @ianxm.

```
$ ihx -a -js # the -a is because Windows drops the first argument
haxe interactive shell v0.4.0
running in nodejs mode
type "help" for help
>> trace("hello world!");
error: Accessing this field requires a system platform (php,neko,cpp,etc.)

>> addlib hxnodejs
added lib: hxnodejs

>> trace("hello world!");
IhxProgram_8245.hx:10: hello world!
```

trace() and other `sys` operations are implemented by `hxnodejs`, but won't work unless the user adds that library to the ihx session. I can see arguments on both sides for wanting to make `-lib hxnodejs` a default flag for running IHx in js mode. It would be more convenient to know trace() and other fundamentals will just work, but also, it does require `haxelib install hxnodejs` first, and I don't think we can automate that installation.

**Comment by NQNStudios** [comment]
Actually... I guess we *could* automate the installation of hxnodejs by making it a dependency of ihx.

**Comment by ianxm** [comment]
I merged this. I didn't want to take the dependency on hxnodejs. I added a note to the readme.

**Comment by NQNStudios** [comment]
Thanks! Having these eval modes in there will be super useful for me!

**Pull request closed without merging**
